#!/bin/sh
#DO NOT FORGET!!! TO set the database-name, backupPATH and mpass(mariadb oneadmin user password) and  muser(user for databse backup) variables accordingly
NOW=$(date '+%d%m%Y')
GZIP=$(which gzip)
MYSQLDUMP=$(which mysqldump)
### MySQL Server Login info ###
MHOST=127.0.0.1
MUSER=oneadmin
BFOLD=/backup/daily
DFOLD=/backup/hourly
DATABASE=opennebula
$MYSQLDUMP -h $MHOST -u $MUSER --log-error=/var/log/mariadb/mdbdump.log --databases $DATABASE | $GZIP -9 > $BFOLD/backup-$NOW.sql.gz
rm -rf "$DFOLD"/*
