#
#-
# Copyright (c) 2015  StorPool.
# All rights reserved.
#
TARGET_HOST = "controller"
BIND_HOST = "0.0.0.0"


KEYSTONE_PORT_REAL  = 35357
KEYSTONE_PORT_PROXY = 36000

NOVA_PORT_REAL  = 8774
NOVA_PORT_PROXY = 36001

CINDER_PORT_REAL  = 8776
CINDER_PORT_PROXY = 36002


KEYSTONE_REMAP = {
	'nova': { NOVA_PORT_REAL: NOVA_PORT_PROXY },
#	'cinder': { CINDER_PORT_REAL: CINDER_PORT_PROXY },
}

STORPOOL_IMAGE_TRUE = "1"
