#!/bin/bash

# shellcheck source=tools/update/update_functions.sh
source /usr/lib/storpool/update_functions.sh

usage(){
	cat <<EOUSAGE

${bold}Usage: $0 [--force] [module1] [module2] ... --yes${norm}

Stops all running StorPool services and attempts to reload the:
	 - storpool_rdma
	 - storpool_disk
	 - storpool_bd
	 - storpool_pci

		kernel modules.

	${bold}[-h|--help]${norm}	- prints this message
	${bold}[moduleN]${norm} - attempts to also reload module after

	${bold}--yes${norm} - required to actually perform the reload
	${bold}--no-cgroup-check${norm} - skip the check that the cgroups exist (${bold}UNSAFE${norm}, please make sure you know what you are doing)

EOUSAGE
}

unset forceflag modules nocgroups proceedf
if [[ -n "$*" ]]; then
	while test -n "$1"; do
		case "$1" in
			-h|--help|usage|help)
				usage
				exit 0
				shift
				;;
			--no-cgroups-check)
				nocgroups=1
				shift
				;;
			--yes)
				proceedf=1
				shift
				;;
			--force)
				forceflag=1
				shift
				;;
			*)
				if chkloaded "$1"; then
					modules+=("$1")
				else
					echo "${bold}${1}${norm} missing or not loaded"
				fi
				shift
				;;
		esac
	done
fi

allservices=($(getservices "all"))
chkprelinked "${allservices[*]}"

chkifaces "$forceflag"

if [[ -z $proceedf ]]; then
	echo "Please use '--yes' to reload" 1>&2
	exit 1
fi

unset running
running=($(getrunning "${allservices[*]}"))
echo -e "Running services:\n${running[*]}"

chkhugepages "${running[*]}"

chkcgroups "${running[*]}"

if _in "storpool_block" "${running[*]}"; then
	exp=1
else
	exp=0
fi
if [ -z "$forceflag" ] && lsmod | awk -v ex="$exp" '$1 == "storpool_bd" && $3 > ex' | grep -Eqe '^'; then
	cat 1>&2 <<EOERR
The storpool_bd kernel module's refcount is too large, some volumes must be open;
rmmod storpool_bd ${bold}will${norm} fail!
Pass "--force" as the first argument to proceed anyway
EOERR
	exit 1
fi

stopservices "${running[@]}"

unset spmodules
spmodules=("storpool_pci" "storpool_disk" "storpool_bd" "storpool_rdma")

unloadmodules "${spmodules[@]}" "${modules[@]}"

if lsmod | grep -Fqe "storpool_vf"; then
	unloadmodules "storpool_vf"
fi

workingmodules=$(lsmod | grep -Fe storpool_)
if [ -n "$workingmodules" ]; then
	echo -e " ${bold}The following modules failed to unload:\n	${workingmodules}${norm}\n"
fi

loadmodules "${modules[@]}"

startservices "${running[@]}"

for spmodule in "${spmodules[@]}"; do
	printmodversion "$spmodule"
done
